spring.application.name=db_EcoShield
spring.datasource.url=jdbc:postgresql://localhost:5432/db_EcoShield
spring.datasource.username=postgres
spring.datasource.password=cinemaparadiso
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#No envia el trace al usuario cuando hay error.
server.error.include-stacktrace=never

jwt.secret=bTVQnSwlBT/OPKsvB1LRNvnFpWs4EmHX6lj3w92AL0aqeyJk3zj6LsxNpMSMF+u0CaXHNcfkCA2gSZxOx9lCZw==
jwt.expiration-minutes=120