spring.application.name=db_EcoShield
spring.datasource.url=jdbc:postgresql://localhost:5432/db_EcoShield
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#No envia el trace al usuario cuando hay error.
server.error.include-stacktrace=never

jwt.secret=bTVQnSwlBT/OPKsvB1LRNvnFpWs4EmHX6lj3w92AL0aqeyJk3zj6LsxNpMSMF+u0CaXHNcfkCA2gSZxOx9lCZw==
jwt.expiration-minutes=120

logging.level.org.springframework.security=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud-name=dsm9krdik
cloudinary.api.key=483251589917696
cloudinary.api.secret=6R8kzvpaVBhW2tE6F4EUCeovGT8

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ecoshieldservice666@gmail.com
spring.mail.password=nqeyvalmszvargde
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

gemini.apiKey=AIzaSyBGb_6RFjVgkiPAGAm7eyde05vS7LdMknk

# app.reset.base-url=
app.reset.expose-token=true