-- Roles
INSERT INTO rol (rolnombre, roldescripcion) VALUES ('USER', 'Rol por defecto de usuarios');
INSERT INTO rol (rolnombre, roldescripcion) VALUES ('ADMIN', 'Rol por defecto para admins');

-- Usuarios
INSERT INTO usuario (rolid, usuarionombre, usuariocorreo, usuariocontrasena, usuarioestado, usuariofotoperfil, usuariopais, usuariofecharegistro) VALUES (2, 'Admin', 'admin@gmail.com', '$2a$12$rpcw1mC92T6qRn8dHaY6X.xquIhHAmG05y8KxJYjpTN5GAfGxaKT2', 'ACTIVO', NULL, 'PERU', NOW());
INSERT INTO usuario (rolid, usuarionombre, usuariocorreo, usuariocontrasena, usuarioestado, usuariofotoperfil, usuariopais, usuariofecharegistro) VALUES (1, 'Gerardo Chávez', 'gerardo@gmail.com', '$2a$12$sFAVQT6RA.B8IZLWxsbh9eSRXnz.0rG3joDLYLnEU6VmMowZwOBF.', 'ACTIVO', NULL, 'PERU', NOW());
INSERT INTO usuario (rolid, usuarionombre, usuariocorreo, usuariocontrasena, usuarioestado, usuariofotoperfil, usuariopais, usuariofecharegistro) VALUES (1, 'María López', 'maria@gmail.com', '$2a$12$A0RI3hD8OdX3fLQx1JnQGeWXSVQ2yPE.Gangh04YLaLfYI/nMTFwG', 'ACTIVO', NULL, 'PERU', NOW());
INSERT INTO usuario (rolid, usuarionombre, usuariocorreo, usuariocontrasena, usuarioestado, usuariofotoperfil, usuariopais, usuariofecharegistro) VALUES (1, 'Carlos Pérez', 'carlos@gmail.com', '$2a$12$JEO7Vxu0w7licD4ae9Rxx.omA5mL6u70y4zilNOfmWyCfunYAhZK6', 'ACTIVO', NULL, 'CHILE', NOW());
INSERT INTO usuario (rolid, usuarionombre, usuariocorreo, usuariocontrasena, usuarioestado, usuariofotoperfil, usuariopais, usuariofecharegistro) VALUES (1, 'Luis Fernández', 'luis@gmail.com', '$2a$12$ervBS/vO18LMWB68pc.5L.1BmxTGx61vxy7/sAhdI3AICvfOIflSC', 'INACTIVO', NULL, 'ARGENTINA', NOW());

-- Plagas de ejemplo
INSERT INTO plaga (plaganombre, plaganombrecientifico, plagatipo,plagadescripcion, plagasintomas, plagatratamiento,plagacausas, plagaprevenciones, plagafoto,temporada, severidad) VALUES('Pulgón', 'Aphididae', 'INSECTO','Insecto pequeño que se alimenta de la savia de las plantas.','Hojas enrolladas, amarillentas y pegajosas por melaza.','Aplicación de jabón potásico o liberación de mariquitas.','Exceso de fertilización nitrogenada.','Rotación de cultivos y eliminación de maleza.','https://example.com/img/plagas/pulgon.jpg','PRIMAVERA', 'MODERADA'),(    'Mosca blanca', 'Trialeurodes vaporariorum', 'INSECTO',    'Pequeño insecto volador que afecta principalmente cultivos hortícolas.',    'Manchas amarillas en hojas, debilitamiento de la planta.',    'Uso de trampas cromáticas y control biológico con Encarsia formosa.',    'Ambientes cálidos y húmedos.',    'Ventilación adecuada en invernaderos.',    'https://example.com/img/plagas/mosca_blanca.jpg',    'VERANO', 'GRAVE')
INSERT INTO enfermedad (enfermedadnombre, enfermedadnombrecientifico, enfermedadtipo,enfermedaddescripcion, enfermedadsintomas, enfermedadtratamiento,enfermedadcausas, enfermedadprevenciones, enfermedadfoto,temporada, severidad) VALUES ('Oídio', 'Erysiphe necator', 'HONGO','Enfermedad fúngica que afecta hojas y tallos, generando polvo blanco.','Manchas blancas polvorientas en hojas, tallos y frutos.','Aplicar fungicidas específicos y mejorar ventilación del cultivo.','Alta humedad y poca circulación de aire.','Podar zonas afectadas y evitar exceso de riego.','https://example.com/img/enfermedades/oidio.jpg','VERANO', 'MODERADA');
INSERT INTO enfermedad (enfermedadnombre, enfermedadnombrecientifico, enfermedadtipo,enfermedaddescripcion, enfermedadsintomas, enfermedadtratamiento,enfermedadcausas, enfermedadprevenciones, enfermedadfoto,temporada, severidad) VALUES ('Botritis', 'Botrytis cinerea', 'HONGO','Moho gris que ataca flores y frutos en condiciones de humedad.','Manchas marrones con moho gris, caída de flores.','Retiro de partes afectadas y uso de fungicidas.','Exceso de humedad y bajas temperaturas.','Mejorar ventilación e implementar riego controlado.','https://example.com/img/enfermedades/botritis.jpg','OTOÑO', 'GRAVE');
INSERT INTO enfermedad (enfermedadnombre, enfermedadnombrecientifico, enfermedadtipo,enfermedaddescripcion, enfermedadsintomas, enfermedadtratamiento,enfermedadcausas, enfermedadprevenciones, enfermedadfoto,temporada, severidad) VALUES ('Mancha bacteriana', 'Xanthomonas campestris', 'BACTERIA','Infección bacteriana que genera manchas oscuras en hojas y frutos.','Manchas marrones rodeadas de halo amarillo.','Uso de bactericidas a base de cobre.','Alta humedad y heridas en tejidos de la planta.','Rotación de cultivos y semillas certificadas.','https://example.com/img/enfermedades/mancha_bacteriana.jpg','PRIMAVERA', 'MODERADA');
INSERT INTO enfermedad (enfermedadnombre, enfermedadnombrecientifico, enfermedadtipo,enfermedaddescripcion, enfermedadsintomas, enfermedadtratamiento,enfermedadcausas, enfermedadprevenciones, enfermedadfoto,temporada, severidad) VALUES ('Virus del mosaico del pepino', 'Cucumber mosaic virus (CMV)', 'VIRUS','Virus que afecta diversas hortalizas, provocando mosaicos en hojas.','Hojas con mosaicos amarillos y deformaciones en frutos.','No existe tratamiento directo, solo control de vectores.','Transmisión por pulgones y semillas infectadas.','Controlar plagas transmisoras y usar semillas libres de virus.','https://example.com/img/enfermedades/mosaico_pepino.jpg','VERANO', 'LEVE');